# Generated by Django 5.0.6 on 2024-07-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavsum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_sel', models.DateField(auto_now_add=True)),
                ('mavsum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegitables.mavsum')),
                ('typee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegitables.type')),
            ],
        ),
        migrations.CreateModel(
            name='Vegitable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_sel', models.DateField(auto_now_add=True)),
                ('mavsum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegitables.mavsum')),
                ('typee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegitables.type')),
            ],
        ),
    ]
