# Generated by Django 5.0.6 on 2024-07-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fruit_images/'),
        ),
        migrations.AddField(
            model_name='vegitable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vegitables_images/'),
        ),
    ]
