# Generated by Django 5.0.6 on 2024-07-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0002_fruit_image_vegitable_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vegitable',
            options={'ordering': ['id']},
        ),
    ]
