# Generated by Django 5.0.6 on 2024-07-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vegitable',
        ),
    ]
