# Generated by Django 5.0.6 on 2024-07-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('vegitables', '0002_fruit_image_vegitable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='fruit',
            field=models.ManyToManyField(to='vegitables.fruit'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='vegitable',
            field=models.ManyToManyField(to='vegitables.vegitable'),
        ),
    ]
